### ISSUE TITLE
"Alter" throws error in validForms

### ISSUE THREAD

**Issue by silentrob** [morungos/wordnet#6] opened 2015-04-08 01:34 UTC
it 'should succeed for alter', (done) ->
      wordnet.validForms 'alter', (results) ->
        should.exist(results)
        done()

Message:
    Length extends beyond buffer
Details:
    domain: [object Object]
    domainThrown: true
Stack:
Error: Length extends beyond buffer
  at Object.fs.read (fs.js:468:11)
  at Object.fs.read (/Users/robellis/projects/bot/wordnet/node_modules/gulp-mocha/node_modules/mocha/node_modules/glob/node_modules/graceful-fs/polyfills.js:210:15)
  at appendLineChar (/Users/robellis/projects/bot/wordnet/lib/wordnet_file.js:12:13)
  at /Users/robellis/projects/bot/wordnet/lib/wordnet_file.js:24:14
  at callback (/Users/robellis/projects/bot/wordnet/node_modules/gulp-mocha/node_modules/mocha/node_modules/glob/node_modules/graceful-fs/polyfills.js:207:17)
  at Object.wrapper [as oncomplete] (fs.js:465:17)

I tried it on Node 0.10.x and 0.12.x

**Comment by morungos** [comment] 2015-04-08 02:14
Yes, easy to reproduce. This one really is deep in the guts of Wordnet, probably in the file I/O optimization and buffering logic (given we're hearing about buffers). A direct lookup on `alter#v` also fails, which confirms that.

**Comment by silentrob** [comment] 2015-04-08 02:23
I saw that as well, given the stack trace (appendLineChar) Ive clearly posted this issue on the wrong repo. (again) sorry.

I will see if I can re-create the issue on natural wordnet and post an issue there as well - or perhaps a patch.

**Comment by morungos** [comment] 2015-04-08 02:30
The logic problem is definitely in appendLineChar. I made a lot of changes to the logic there, basically because it wasn't reading in blocks in the natural version, and the performance was fairly awful when I pushed it. I can see what's wrong, but I'll fix tomorrow. Mainly, an additional buffer start parameter is needed to make the recursive calls right. The original natural implementation might even be immune. The name of this function is also totally wrong now, as it does recursive blocked reads starting at 4k. This might be the first time that's been exceeded.

**Comment by silentrob** [comment] 2015-04-08 03:04
There is no urgency on this. So I wrote the original wordnet bindings years ago and Chris re-wrote it and made is significantly more efficient. but still left room for improvement. I'm surprised this hasn't been caught yet to be honest.

I feel like it could benefit from a small LRU cache as well, maybe store the last 2000 lookups?!

**Comment by morungos** [comment] 2015-04-08 12:28
Turned out simpler than I thought. Fixed in 0.1.7

**Closed by morungos** 2015-04-08 12:28 UTC

**Comment by morungos** [comment] 2015-04-08 14:46
Plus, I should say: total thanks for getting this started. I really needed a Wordnet on node.js, and although I've brought in a bunch of interfaces from a Perl API (e.g., validForms) I'd never have got anywhere without having the basic logic to start with. While I love and use the natural API, I'm not wholly sure that Wordnet wouldn't be better as distinct module anyways, even if it's then brought in as a dependency. And as I'm using it a lot now, any other suggestions would be wonderful. I'll get to the caching soon, as I'll need that too soon.
